repos:
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
    # See:
    # * https://black.readthedocs.io/en/stable/version_control_integration.html
    # * https://github.com/ambv/black/blob/master/.pre-commit-hooks.yaml
