sudo: false
language: python
dist: xenial  # required for Python >= 3.7

python:
  - "3.5"
  - "3.7"

matrix:
  include:
    - python: "3.7"
      env:
        - TOXENV=style
    - python: "3.7"
      env:
        - TOXENV=type

before_install:
  - pip install --quiet tox

script:
  - tox

notifications:
  email: false
