sudo: false
language: python
dist: xenial  # required for Python >= 3.7

python:
  - "3.5"
  - "3.7"

matrix:
  include:
    - &check
      python: "3.7"
      env:
        - TOXENV=style
      script:
        - tox
    - <<: *check
      env:
        - TOXENV=type

before_install:
  - pip install --quiet tox coveralls

script:
  - tox -- --cov=genrun

after_success:
  - coveralls

notifications:
  email: false
